version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smart_note
      - POSTGRES_PORT=5432
      - SECRET_KEY=${SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_URL=${OPENAI_API_URL}
    depends_on:
      - db
    volumes:
      - ./app:/app/app
    networks:
      - smart_note_network
  # healthcheck:
  #   test: ["CMD", "curl", "-f", "http://localhost:8000/"]
  #   interval: 30s
  #   timeout: 10s
  #   retries: 3

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=smart_note
    ports:
      - "5432:5432"
    networks:
      - smart_note_network
# healthcheck:
#   test: ["CMD-SHELL", "pg_isready -U postgres"]
#   interval: 10s
#   timeout: 5s
#   retries: 5

volumes:
  postgres_data:

networks:
  smart_note_network:
    driver: bridge 